export const STORAGE_KEY = "tft-set17-flowchart-maker-state";
export const DATA_URL = "https://raw.communitydragon.org/latest/cdragon/tft/en_us.json";
export const PLANNER_URL = "https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/tftchampions-teamplanner.json";
export const LOCAL_ASSET_BASE = "./assets";

export const EXCLUDED_UNIT_NAMES = new Set([
  "mini black hole",
  "golem",
  "rift scuttler",
  "scuttle crab",
  "training dummy",
]);

export const itemApiNames = {
  "B.F. Sword": "TFT_Item_BFSword",
  "Recurve Bow": "TFT_Item_RecurveBow",
  "Needlessly Large Rod": "TFT_Item_NeedlesslyLargeRod",
  "Tear of the Goddess": "TFT_Item_TearOfTheGoddess",
  "Chain Vest": "TFT_Item_ChainVest",
  "Negatron Cloak": "TFT_Item_NegatronCloak",
  "Giant's Belt": "TFT_Item_GiantsBelt",
  "Sparring Gloves": "TFT_Item_SparringGloves",
  Spatula: "TFT_Item_Spatula",
  "Frying Pan": "TFT_Item_FryingPan",
};

export const fallbackUnits = [
  { name: "Aatrox", cost: 1, traits: ["N.O.V.A.", "Bastion"] },
  { name: "Briar", cost: 1, traits: ["Anima", "Primordian", "Rogue"] },
  { name: "Caitlyn", cost: 1, traits: ["N.O.V.A.", "Fateweaver"] },
  { name: "Cho'Gath", cost: 1, traits: ["Dark Star", "Brawler"] },
  { name: "Ezreal", cost: 1, traits: ["Timebreaker", "Sniper"] },
  { name: "Leona", cost: 1, traits: ["Arbiter", "Vanguard"] },
  { name: "Lissandra", cost: 1, traits: ["Dark Star", "Shepherd", "Replicator"] },
  { name: "Nasus", cost: 1, traits: ["Space Groove", "Vanguard"] },
  { name: "Poppy", cost: 1, traits: ["Meeple", "Bastion"] },
  { name: "Talon", cost: 1, traits: ["Stargazer", "Rogue"] },
  { name: "Teemo", cost: 1, traits: ["Space Groove", "Shepherd"] },
  { name: "Twisted Fate", cost: 1, traits: ["Stargazer", "Fateweaver"] },
  { name: "Veigar", cost: 1, traits: ["Meeple", "Replicator"] },
  { name: "Akali", cost: 2, traits: ["N.O.V.A.", "Marauder"] },
  { name: "Bel'Veth", cost: 2, traits: ["Primordian", "Challenger", "Marauder"] },
  { name: "Gnar", cost: 2, traits: ["Meeple", "Sniper"] },
  { name: "Gragas", cost: 2, traits: ["Psionic", "Brawler"] },
  { name: "Gwen", cost: 2, traits: ["Space Groove", "Rogue"] },
  { name: "Jax", cost: 2, traits: ["Stargazer", "Bastion"] },
  { name: "Jinx", cost: 2, traits: ["Anima", "Challenger"] },
  { name: "Meepsie", cost: 2, traits: ["Meeple", "Shepherd", "Voyager"] },
  { name: "Milio", cost: 2, traits: ["Timebreaker", "Fateweaver"] },
  { name: "Pantheon", cost: 2, traits: ["Timebreaker", "Brawler", "Replicator"] },
  { name: "Pyke", cost: 2, traits: ["Psionic", "Voyager"] },
  { name: "Zoe", cost: 2, traits: ["Arbiter", "Conduit"] },
  { name: "Aurora", cost: 3, traits: ["Anima", "Voyager"] },
  { name: "Diana", cost: 3, traits: ["Arbiter", "Challenger"] },
  { name: "Fizz", cost: 3, traits: ["Meeple", "Rogue"] },
  { name: "Illaoi", cost: 3, traits: ["Anima", "Vanguard", "Shepherd"] },
  { name: "Kai'Sa", cost: 3, traits: ["Dark Star", "Rogue"] },
  { name: "Lulu", cost: 3, traits: ["Stargazer", "Replicator"] },
  { name: "Maokai", cost: 3, traits: ["N.O.V.A.", "Brawler"] },
  { name: "Miss Fortune", cost: 3, traits: ["Gun Goddess", "Choose Trait"] },
  { name: "Ornn", cost: 3, traits: ["Space Groove", "Bastion"] },
  { name: "Samira", cost: 3, traits: ["Space Groove", "Sniper"] },
  { name: "Urgot", cost: 3, traits: ["Mecha", "Brawler", "Marauder"] },
  { name: "Viktor", cost: 3, traits: ["Psionic", "Conduit"] },
  { name: "Aurelion Sol", cost: 4, traits: ["Mecha", "Conduit"] },
  { name: "Corki", cost: 4, traits: ["Meeple", "Fateweaver"] },
  { name: "Karma", cost: 4, traits: ["Dark Star", "Voyager"] },
  { name: "Kindred", cost: 4, traits: ["N.O.V.A.", "Challenger"] },
  { name: "LeBlanc", cost: 4, traits: ["Arbiter", "Shepherd"] },
  { name: "Master Yi", cost: 4, traits: ["Psionic", "Marauder"] },
  { name: "Nami", cost: 4, traits: ["Space Groove", "Replicator"] },
  { name: "Nunu & Willump", cost: 4, traits: ["Stargazer", "Vanguard"] },
  { name: "Rammus", cost: 4, traits: ["Meeple", "Bastion"] },
  { name: "Riven", cost: 4, traits: ["Timebreaker", "Rogue"] },
  { name: "The Mighty Mech", cost: 4, traits: ["Mecha", "Voyager"] },
  { name: "Bard", cost: 5, traits: ["Meeple", "Conduit"] },
  { name: "Blitzcrank", cost: 5, traits: ["Party Animal", "Space Groove", "Vanguard"] },
  { name: "Fiora", cost: 5, traits: ["Divine Duelist", "Anima", "Marauder"] },
  { name: "Jhin", cost: 5, traits: ["Dark Star", "Eradicator", "Sniper"] },
  { name: "Morgana", cost: 5, traits: ["Dark Lady"] },
  { name: "Shen", cost: 5, traits: ["Bulwark", "Bastion"] },
  { name: "Sona", cost: 5, traits: ["Commander", "Psionic", "Shepherd"] },
  { name: "Vex", cost: 5, traits: ["Doomer"] },
  { name: "Zed", cost: 5, traits: ["Galaxy Hunter"] },
];

export const fallbackItems = [
  { name: "B.F. Sword" },
  { name: "Recurve Bow" },
  { name: "Needlessly Large Rod" },
  { name: "Tear of the Goddess" },
  { name: "Chain Vest" },
  { name: "Negatron Cloak" },
  { name: "Giant's Belt" },
  { name: "Sparring Gloves" },
  { name: "Spatula" },
  { name: "Frying Pan" },
];

export const seededPaths = [];
